### ISSUE TITLE
Incorrect callahan score

### ISSUE THREAD

**Issue by wingleungchan** [kevinhughes27/parity-server#139] opened 2017-11-16 17:31 UTC
The stats show that Tom scored a callahan in Week 1. This is incorrect.

**Comment by patrickkenzie** [comment] 2017-11-16 18:32
Yup, looks like the issue is here:

https://github.com/kevinhughes27/parity-server/blob/a92cd2beee6902cc814c52de7c92e47937e21a69/data/ocua_17-18/week1_game1.json#L1927-L1936

Missing a player picking up and throwing the point, presumably.

For the record, I'd say this is theoretically valid data: O player bobbles a catch, and the D player catches it for a callahan would get recorded like this.

**Comment by kevinhughes27** [comment] 2017-11-16 23:50
I would agree the data looks fine and presumably this is human error. We can ask Tom or someone from the game to try and figure out who threw it

**Comment by kevinhughes27** [comment] 2017-12-08 19:30
No update from the stats keepers. closing.

**Closed by kevinhughes27** 2017-12-08 19:30 UTC
